version: '3.7'

services:
  keycloak:
    build:
      context: .
      dockerfile: ./keycloak/Dockerfile
      args:
        ADMIN_USERNAME: ${KEYCLOAK_USERNAME}
        ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}             
    container_name: inbolso-keycloak
    restart: unless-stopped    
    environment:      
      - PROXY_ADDRESS_FORWARDING=true  #important for reverse proxy
      - DB_VENDOR=postgres
      - DB_ADDR=${PG_HOST}
      - DB_PORT=${PG_PORT}
      - DB_SCHEMA=${PG_SCHEMA}
      - DB_DATABASE=${PG_DB}
      - DB_USER=${PG_USERNAME}
      - DB_PASSWORD=${PG_PASSWORD}
      - JAVA_OPTS=-server -Xms1024m -Xmx1024m
    volumes:
      - ./keycloak/keycloak-bcrypt-1.5.0.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-bcrypt-1.5.0.jar
      - ./keycloak/themes/inbolso:/opt/jboss/keycloak/themes/inbolso
    ports:
      - 8080:8080
    
# Adicione no seu bash/zsh profile as variáveis do keycloak. 
# Ex:
# KEYCLOAK_USERNAME=meu-user
# KEYCLOAK_PASSWORD=minha-senha
#
# Se for testar local, descomente o extra_hosts